### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by planemad** [mapbox/vtvalidate#24]
This error suddenly started popping up for me over the last 4 days on a code which runs perfectly for everyone else.

Commenting out vtvalidate allowed the rest of the program to function without errors. This is using node v6.

```
module.js:604
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/arun/GitHub/Mapbox/poi-tileset/node_modules/@mapbox/vtvalidate/lib/index.js:3:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

Tried online resolutions for this type of error without success- clearing node_modules+cache and reinstalling packages, brew update+upgrade, latest osx update + xcode, reinstalling node.

Also I don't recall any software changes on my system that could have suddenly caused this error to appear, except for a prompt telling me to update OSX. 🤔 

Using node v8, the error is:

```
Error: dlopen(/Users/arun/Github/Mapbox/poi-tileset/node_modules/@mapbox/vtvalidate/lib/binding/module.node, 1): Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
  Referenced from: /Users/arun/Github/Mapbox/poi-tileset/node_modules/@mapbox/vtvalidate/lib/binding/module.node
  Expected in: flat namespace
 in /Users/arun/Github/Mapbox/poi-tileset/node_modules/@mapbox/vtvalidate/lib/binding/module.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/arun/Github/Mapbox/poi-tileset/node_modules/@mapbox/vtvalidate/lib/index.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```

cc @GretaCB @lukasmartinelli

**Comment by mapsam** [comment]
@planemad Have you seen this pop up again? The incorrect symbol error `Symbol not found: __ZN2v816...` suggests the node version might have changed but the binary for vtvalidate was not reinstalled for that particular version.

**Comment by planemad** [comment]
@mapsam thanks, this was resolved 👍
